language: node_js
dist: trusty
git:
  depth: 10
  sparse_checkout: tools/sparse-checkout.template
node_js:
  - "8"
cache:
  bundler: true
  apt: true
  directories:
    - node_modules
notifications:
  email: false
sudo: required
branches:
  only:
    - travis
    
